[package]
name = "todo"
version = "0.1.0"
edition = "2024"
authors = ["Junaid Sultan <contact@junaidsultan.com>"]
description = "Simple todo with daily tasks. Library + CLI"
licence = "MIT"
repository = "https://github.com/junaidsultanxyz/todo-rust"

[dependencies]
chrono = { version = "0.4.45", features = ["serde"] }
clap = { version = "4.6.7", features = ["derive"] }
directories = "6.0.0"
nanoid = "0.5.0"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
